### ISSUE TITLE
Is this a usable integration already?

### ISSUE THREAD

**Issue by davidrustingha** [ckarrie/ckw-ha-gs108e#1]
I recently bought a GS108E and would like to integrate it. Can I use it already?

**Comment by ckarrie** [comment]
Hi, yes it was usable. But unfortunately it doesn't work with recent HomeAssistant versions. I have to figure out why. But I'm still interested to get this back working.

**Comment by ckarrie** [comment]
Nevermind, it's still "usable" (stops working after few days, but still works with recent HomeAssistant versions).
![image](https://user-images.githubusercontent.com/4140156/118571943-8b41b180-b77f-11eb-878b-2d63fe5222ed.png)
