### ISSUE TITLE
[FR] count data for each port

### ISSUE THREAD

**Issue by el97** [ckarrie/ckw-ha-gs108e#10]
A useful feature would be if there is a counter that shows the total received/transferred. There is sensors called received/transferred for each port but it resets after a few seconds. it looks like it's supposed to count traffic though so it might be a bug that it resets.

A workaround would be to make helpers for each port that count the traffic but it would be great if it already was a function when you set up the integration.

**Comment by ckarrie** [comment]
Hi @el97 the `port_1_traffic_transferred` and `port_1_traffic_received` should be for that.
But it seems to be a bug.

I'll take a look into it.

**Comment by ckarrie** [comment]
Ha, dammit, looked at my wrong Switch. Sorry.
It's not a bug, `port_1_traffic_transferred` and `port_1_traffic_received` works as expected (delta MB between each request).

Update coming soon

**Comment by ckarrie** [comment]
@el97 added total tx and rx

![image](https://user-images.githubusercontent.com/4140156/221428124-5e10868d-c869-478b-b3ee-c1581cd5fa95.png)

you can change the displayed Unit of Measurement in the sensor settings

![image](https://user-images.githubusercontent.com/4140156/221428195-2494b654-f109-474a-8314-076b7f1f66ff.png)
