### ISSUE TITLE
Add "linked speed" attribute

### ISSUE THREAD

**Issue by vegedb** [ckarrie/ckw-ha-gs108e#11]
![image](https://user-images.githubusercontent.com/72070424/231196614-8e0c91c1-9248-40f3-aff2-89b80ff6a1c1.png)

Problem: Due to cable problems, sometimes it changes from 1000M to 100M.
It can be fixed by replugging the cable, intermittent issue.

Purpose: To detect any changes from 1000M to 100M and send notification through home assistant.

**Comment by ckarrie** [comment]
Good Idea, can give it a try

**Comment by ckarrie** [comment]
havn't forget you, still found no time unfortunately

**Comment by ckarrie** [comment]
Hi @vegedb , check out v0.5.3 if it works for you?

![image](https://github.com/ckarrie/ckw-ha-gs108e/assets/4140156/46d28dd8-f28f-4892-9eea-a7c0fb7ac747)
