### ISSUE TITLE
port data is empty

### ISSUE THREAD

**Issue by tlgenius** [ckarrie/ckw-ha-gs108e#15]
thank you for your work !
I just installed HAS (I was on Domoticz) and I installed your script ckw-ha-gs108e

But it doesn't work,
the diagnosis is ok but not the data on the ports

bootloader V2.06.01
Firmware V2.06.24EN

HAS
Core 2024.4.1
Supervisor 2024.03.1
Operating System 12.1
User interface 20240404.1

**Comment by gdi0110** [comment]
I had the same issue and and have the same bootloader & firmware versions. 

If change the Bootloader version check to a lower version, I get values from the switch:
https://github.com/ckarrie/ckw-ha-gs108e/blob/1692d54d829b86f50c37bc87bd5b3ced7b261add/custom_components/ckw_hass_gs108e/gs108e/__init__.py#L122

To:
`        if self._switch_bootloader in ['V2.06.01']:`

Or another way to fix would be to see why XPath is not returning the value in this block of code:
https://github.com/ckarrie/ckw-ha-gs108e/blob/1692d54d829b86f50c37bc87bd5b3ced7b261add/custom_components/ckw_hass_gs108e/gs108e/__init__.py#L132-L135

Changing the Bootloader was a quick fix for me for now as I'm using this code outside of HomeAssistant

**Comment by ckarrie** [comment]
Could you check out v0.5.3 if it works now?

**Comment by gdi0110** [comment]
@ckarrie Sorry for the late response, just say the notification. Works for my GS108E with the latest (v0.6.1) release


```
Bootloader Version: V2.06.01
Firmware Version: V2.06.24EN

Home Assistant: 2024.7.3
```
