### ISSUE TITLE
Platform error sensor.ckw_hass_gs108e - Integration 'ckw_hass_gs108e' not found.

### ISSUE THREAD

**Issue by davidrustingha** [ckarrie/ckw-ha-gs108e#2]
Hi,

I have added the folder to my 'custom_components' folder like you would normally. But I still get this error when checking my config.

What am I doing wrong?

`Platform error sensor.ckw_hass_gs108e - Integration 'ckw_hass_gs108e' not found.
`

**Comment by davidrustingha** [comment]
I have found out what the problem seemed to be. In the manifest.json should be a 'version' key. I have edited my own manifest file and restarted Home Assistant but then my UI doesn't load and its stuck somewhere in between. I couldnt find any relevant errors. 

Have you had this error? How did you load the integration without the version key?

**Comment by ckarrie** [comment]
I get the same errors recently, maybe HASS changed something

`Platform error sensor.ckw_hass_gs108e - Integration 'ckw_hass_gs108e' not found.`

**Comment by ckarrie** [comment]
Maybe this could fix it https://github.com/home-assistant/core/issues/43518

**Comment by ckarrie** [comment]
Updated the manifest.json and it works for me now

**Comment by ckarrie** [comment]
fixed in 665856b
