### ISSUE TITLE
Issue in HA start

### ISSUE THREAD

**Issue by SruiSan** [ckarrie/ckw-ha-gs108e#3]
Hi! 

First of all, thanks for you job.

I try to use this scripts, but when I define the hosts in yaml file, and I restart the HA, it not start

I want to know if still works, or spend some time to debug if the issue is in my side

Thank you!

**Comment by ckarrie** [comment]
Thanks, I saw some breaking changes in the new Switch Firmware some days ago when I updated the Firmware.

I will take a look into it.

**Comment by SvenMartin81** [comment]
hi, I had the same issue with the Netgear GS724T switch

**Comment by Sunspot1230987** [comment]
Same problem here. Which Switch Firmware was still working? I'm running V2.06.14EN. I find firmware versions 2.00.x and 2.06.x

**Comment by SvenMartin81** [comment]
hi, i cannot connect to my switch withhin this integration. There is a fault message. I should check my konfiguration....but the IP and the passwort is correct.

**Comment by ckarrie** [comment]
Could you recheck again? Did some work here https://github.com/ckarrie/ckw-ha-gs108e/issues/6#issuecomment-1374172577

**Comment by SvenMartin81** [comment]
> 

hi, I tested with my GS724T but this appears....There is although a strange standard host defined (192.168.178.5)...which has nothing to do with my network. How can I change this?

**Comment by ckarrie** [comment]
I don't own a GS724T so I can't test it. This integration is tested with GS108E only. 
Yeah, 192.168.178.5 is the current default IP in this integration, I will remove that.

**Comment by SvenMartin81** [comment]
means, if i change this to my switch IP it could be possible to run?

**Comment by ckarrie** [comment]
You can try this integration with your GS724T by re-adding your switch and entering your Switch IP/Password, but I'm quite unconfident that your GS724T will work.
