### ISSUE TITLE
Need better directions

### ISSUE THREAD

**Issue by PerfectBake420** [ckarrie/ckw-ha-gs108e#4]
you have a small set of code that says to add it to the configuration.yaml file but then it has a lot of code after that and does not say where that code needs to be put. Thank you for any assistance you can give.

**Comment by ckarrie** [comment]
I agree, my documentation is bad. 
Will fix it.

**Comment by TimmieVL** [comment]
any idea when the info will be updated?
I try to use the integration and editing the configuration file. but to no avail atm

**Comment by ckarrie** [comment]
Updated the readme and reworked the integration. Please check again.

**Comment by peterpijpelink** [comment]
it is still pretty bad to understand how and what, your readme doesn't show any help at all. Deleted the integration.
